# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ADMIN_ECOMMERCE' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
pod 'SideMenu'
pod 'Alamofire', '~> 5.4'
pod 'SDWebImage', '~> 5.0'
pod 'NVActivityIndicatorView'
pod 'Cosmos'
pod 'DropDown'
pod 'Charts'

  # Pods for ADMIN_ECOMMERCE

end
